### ISSUE TITLE
Is this an upgraded version of Effi-MVS?

### ISSUE THREAD

**Issue by ConquerorXv** [bdwsq1996/Effi-MVS-plus#1]
Thank you for your excellent work Effi-MVS, is there any information about Effi-MVS-plus at the moment? Is it an upgraded version of Effi-MVS, I see on the Tanks and Temples list that Effi-MVS-plus has achieved good ratings. I'm looking forward to your next one!

**Comment by bdwsq1996** [comment]
Thank you for your attention. Our Effi-MVS-plus ("Efficient Multi-view Stereo by Dynamic Cost Volume and Cross-scale Propagation") was recently published online in the TCSVT and is currently in the Early Access phase. You can view our paper at https://ieeexplore.ieee.org/document/10522746. We plan to upload our code in the near future.

**Comment by ConquerorXv** [comment]
Thank you very much, I will read it.
